name: pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-latest

    steps:
      # リポジトリをチェックアウト
      - name: Checkout
        uses: actions/checkout@v2

      # Python環境セットアップ
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      # pytestをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # JUnit形式でpytestの結果を出力
      - name: Run pytest
        run: |
          python -m pytest --junit-xml results/pytest.xml
        continue-on-error: true

      # テスト結果をアップロードする
      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: test_results
          path: results/*.xml

      # テスト結果をダウンロードする
      - name: Download results
        uses: actions/download-artifact@v3
        with:
          name: test_results
          path: artifacts

      # テスト結果をGitHub上で表示する
      - name: display results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml

